name: fluttsec
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  oauth2_client: ^3.2.2
  flutter_data: ^1.5.6
  # Highly RECOMMENDED (but not required) packages
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  hooks_riverpod: ^2.5.1
  file_picker: ^8.0.6
  simple_barcode_scanner: ^0.0.8
  add_2_calendar: ^3.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.1
  dio: ^5.5.0+1
  uuid: ^4.4.0
  shared_preferences: ^2.2.3

  flutter_riverpod: any
  flutter_gen: any
  url_launcher: ^6.3.0
  device_calendar: ^4.3.2
  go_router: ^14.2.1
  equatable: ^2.0.5
  localstorage: ^5.0.0
  intl: ^0.19.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1+2
  rxdart: ^0.28.0
  maps_launcher: ^2.2.1
  fluttertoast: ^8.2.6
  carousel_slider: ^4.2.1
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0 # REQUIRED!

  # Highly RECOMMENDED (but not required) packages
  json_serializable: ^6.4.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
